name: CI - Rust Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            tests/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Dependencies
        run: |
          rustup update stable
          rustup default stable
          rustup component add rust-src rustfmt clippy
          rustup target add wasm32-unknown-unknown
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0

      - name: Clean build
        run: |
          cargo clean
          rm -rf ~/.cargo/registry ~/.cargo/git
          cargo update

      - name: Build Project
        run: cargo build --verbose

      - name: Run Tests
        run: cargo test --verbose
